### ISSUE TITLE
Feature request: Support for ES6 compiling

### ISSUE THREAD

**Issue by watzon** [bdkjones/CodeKit2#562]
It would be really nice if we could just compile the `.es6.js` extension to ES5

**Comment by fujiwaraficc** [comment]
+1

**Comment by calvinjuarez** [comment]
I was just thinking this the other day.  Transpiling would be a killer feature right now.

Babel may be helpful. https://babeljs.io

**Comment by Andreyco** [comment]
Similar to #554

**Comment by watzon** [comment]
+1 please devs!

**Comment by marioluevanos** [comment]
+1

**Comment by fmaida** [comment]
Another +1

**Comment by bdkjones** [comment]
Hey guys. I'm not ignoring you. 

Here's the top-secret info: there's a build of CodeKit with Babel built in and working perfectly. (Among many other popular requests on this GitHub page.) It's not ready for public release yet, but I'm getting close to a closed alpha test, followed by a closed beta, followed by blowing people's minds.

Hang in there. I'll ask for testers on Twitter in probably a month or so.

**Comment by yougotashovel** [comment]
@bdkjones Any updates on the update?

**Comment by Andreyco** [comment]
Do we really want CK to do this? In the end, what are you trying to achieve? With all the respect to CK, isn't out there tool better thank CK to achieve same results? Are you writing app in React? If so, pick Webpack (or Browserify), get yourself hot transformation (hot loading) and use CK for other stuff which it handles just great...
Once again, love CK, awesome job here! :)

**Comment by redler** [comment]
If you're going to go that road, it might make better sense to use something like gulp. I think there are a bunch of nice use cases for Babel support in CK. If you've got a longstanding CK workflow (let's say with less, jshint, and uglify), and you just want to dip your toe into React by folding in a few components, it would be awfully nice to have have your React/jsx code drop right into that same workflow (linted, ES6 transformed, jsx transformed, then all uglified -- along with your regular JS stuff). Likewise, even without React you might want to start adding ES6isms to your JS; if the CK pipeline could pass your JS through Babel, it would make it very easy to jump in with ES6 at your leisure.

**Comment by theskillwithin** [comment]
Plz add this 
https://babeljs.io/

**Comment by t0t** [comment]
I would like it too...

**Comment by adampatterson** [comment]
@bdkjones if you are still looking for testers I would be happy to help. I have 40+ sites with day to day maintenance as well as a handful of React projects in the mix. Gulp/Grunt are driving me insane!

**Comment by bdkjones** [comment]
Soon.

**Comment by grosewarne** [comment]
+1!  Yes please!
I need it for the latest foundation´s version 6.2.0 
https://github.com/zurb/foundation-sites/wiki/Upgrading-to-Foundation-6.2

> The JavaScript is now written in ES2015, which means if you consume the js/ folder of the Foundation package as part of a build process, it will need to be transpiled using Babel.

**Comment by tconroy** [comment]
👍 !!

**Comment by jlmakes** [comment]
The modern JavaScript workflow with CLI task runners is wonderful for advanced and expert developers, but I think CodeKit supporting ES6 transpiling would be an excellent way to help beginners and intermediate developers start using the future of JavaScript.

💯

**Comment by fiunary** [comment]
Just wondering whether CodeKit is still a live project?   I am trying it as a simple alternative to command line stuff but can't get it to work with Foundation 6.2.  It all looks fine but the concatenated js thrown an error in browsers - I thinks it's a Babel thing? Should I just give up on this?

**Comment by bdkjones** [comment]
Oh Christ yes CodeKit is still alive. Version 3 is just about ready to go and has Babel.

**Comment by calvinjuarez** [comment]
^ https://incident57.com/codekit/3/

**Comment by fiunary** [comment]
Thanks Brian I know you closed this but what does this error mean?  
[Error] TypeError: e.indexOf is not a function. (In 'e.indexOf(" ")', 'e.indexOf' is undefined)

**Comment by tconroy** [comment]
@fiunary `e` has no method `indexOf()`... is this related to CodeKit or your own code?

**Comment by fiunary** [comment]
hi @tconroy.  No that's just concatenating query.js and foundation.js

**Comment by bdkjones** [comment]
Babel is required to process JS in Foundation 6.2. It’s all in CodeKit 3, the Foundation team just went to Babel a little ahead of me.

**Comment by fiunary** [comment]
thanks @bdkjones I am finding it hard to find out what best to do.  Is the issue to do with Babel?   The foundation package I have is the one downloaded via Codekit.  Does it not work with Codekit?   Is there a work around?   I have Googled for quite a time but can't find an answer.  Really appreciate the support.

**Comment by tconroy** [comment]
@fiunary you could try and get into the CodeKit 3 beta. https://incident57.com/codekit/3/

**Comment by fiunary** [comment]
@tconroy I don't think i would be usefull!  Anything else to do or is it best to stick with Gulp for the moment?

**Comment by bdkjones** [comment]
Foundation 6.2 works fine with CodeKit 2 as long as you don’t have to process the JS file.

**Comment by fiunary** [comment]
Thanks.  Looking forward to CodeKit3
